Story1 display recent jobs
iO-Academy/2022-jan-fish-job-search pull request #6
Opened 2022-03-09 10:56 UTC by maxwell-01

initial PR review ahead of trainer review

2022-03-09 11:27 UTC, maxwell-01 reviewed
Just one comment for @liamlwrnc to take a look at on the footer

2022-03-09 11:27 UTC, maxwell-01 commented on src/Footer/Footer.js
> +            <footer id="footer" className="footer-1">
@liamlwrnc 
Please can you talk me through why you have 5 divs?
Also, the wireframe shows the footer text inline with the content whereas this footer is not.

2022-03-09 13:40 UTC, norayna commented on public/index.html
>      <title>React App</title>
the title should be something else

2022-03-09 14:42 UTC, norayna commented on src/Main/Main.js
> +export default Main
doesn't seem like there's any reason for this component to exist? with or without it the resulting HTML, CSS & JS generated for the website would be the same

2022-03-09 14:45 UTC, norayna commented on src/JobsContainer/JobsContainer.js
> +export default JobsContainer
doesn't seem like there's any reason for this component to exist? with or without it the resulting HTML, CSS & JS generated for the website would be the same

2022-03-09 15:33 UTC, norayna commented on public/index.html
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossOrig
why do you have both bootstrap 5 and bootstrap 4? 👀

2022-03-09 16:59 UTC, norayna commented on src/Type/Type.js
> +            {(props.type != null) ? <span className={'badge rounded-pill bg-primary'}>{props.type}</span> : ''}
why is it that this component has this check but the Skill component does not have a similar check?

2022-03-09 17:00 UTC, norayna requested changes
looking greattt

2022-03-10 09:51 UTC, norayna requested changes
everything i commented on looks good now, however:

because of the bootstrap change, the job cards don't have enough padding around the content and headings now, see picture of yours and picture of wireframe:
![image](https://user-images.githubusercontent.com/25844355/157636250-49d45bcc-da10-4b97-b010-4d02122fec0a.png)
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/25844355/157636293-98d88a10-56de-4c48-9255-56c88e8f6db3.png">

2022-03-10 10:11 UTC, norayna approved these changes

2022-03-10 10:11 UTC, merged